export enum MessageType {
    GAME_START = "GAME_START",
    GAME_OVER = "GAME_OVER",
    GAME_LOG = "GAME_LOG",
    CREATE_ROOM = "CREATE_ROOM",
    JOIN_ROOM = "JOIN_ROOM",
    PLAYER_JOINED_ROOM = "PLAYER_JOINED_ROOM",
    LEAVE_ROOM = "LEAVE_ROOM",
    PLAYER_LEFT_ROOM = "PLAYER_LEFT_ROOM",
    ROOM_DETAILS = "ROOM_DETAILS"
}
