export enum GameMessageType {
    GAME_START = "GAME_START",
    GAME_OVER = "GAME_OVER",
    ADD_DOMINO = "ADD_DOMINO",
    POSSIBLE_PLAYS = "POSSIBLE_PLAYS",
    HAND = "HAND",
    PACK_EMPTY = "PACK_EMPTY",
    CLEAR_BOARD = "CLEAR_BOARD",
    SCORE = "SCORE",
    ERROR = "ERROR",
    TURN = "TURN",
    PULL = "PULL",
    DOMINO_PLAYED = "DOMINO_PLAYED",
    NEW_ROUND = "NEW_ROUND",
    GAME_LOG = "GAME_LOG",
    PLAYER_DOMINOED = "PLAYER_DOMINOED",
    GAME_BLOCKED = "GAME_BLOCKED"
}
